spring:
  application:
    name: module-2-di-ioc

  flyway:
    baseline-on-migrate: true
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    create-schemas: true
    schemas: module_2_di_ioc
    url: ${DB_JDBC_URL}

  r2dbc:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_R2DBC_URL}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  http:
    codecs:
      log-request-details: true

  webflux:
    base-path: /

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.http.codec: DEBUG

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

jwt:
  password:
    encoder:
      secret: ${JWT_PASSWORD_ENCODER_SECRET:defaultSecretForLocal}
      iteration: 64
      keylength: 254
  secret: ${JWT_SECRET}
  experation: ${JWT_EXPIRATION}
  issuer: ${JWT_ISSUER}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
