services:
  mySql-db:
    image: mysql:8.0.43
    container_name: mySql-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql
    dns_search: .

  mino:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - 9000:9000   # API (для приложений)
      - 9001:9001  # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data

volumes:  # ← Добавляем объявление тома
  mysql_data:
  pg_data:
  ./data/minio:
